// Enum name, Display name,     Win32 code,  Xkb code
X(Escape,    "Escape",          VK_ESCAPE,   XKB_KEY_Escape)
X(Enter,     "Enter",           VK_RETURN,   XKB_KEY_Return)
X(Tab,       "Tab",             VK_TAB   ,   XKB_KEY_Tab)
X(Delete,    "Delete",          VK_DELETE,   XKB_KEY_Delete)
X(Backspace, "Backspace",       VK_BACK  ,   XKB_KEY_BackSpace)
X(Home,      "Home",            VK_HOME ,    XKB_KEY_Home)
X(End,       "End",             VK_END   ,   XKB_KEY_End)
X(Left,      "Left arrow key",  VK_LEFT,     XKB_KEY_Left)
X(Up,        "Up arrow key",    VK_UP,       XKB_KEY_Up)
X(Right,     "Right arrow key", VK_RIGHT,    XKB_KEY_Right)
X(Down,      "Down arrow key",  VK_DOWN,     XKB_KEY_Down)
X(LControl,   "Left Control",         VK_CONTROL,  XKB_KEY_Control_L)
X(RControl,   "Right Control",         VK_CONTROL,  XKB_KEY_Control_R)
X(LShift,     "Left Shift",           VK_SHIFT,    XKB_KEY_Shift_L)
X(RShift,     "Right Shift",           VK_SHIFT,    XKB_KEY_Shift_R)
X(RAlt,       "Left Alt",             VK_MENU,     XKB_KEY_Alt_L)
X(LAlt,       "Right Alt",             VK_MENU,     XKB_KEY_Alt_R)
X(Count,     "INVALID",         0,           0)
